services:
  backend:
    build: .
    container_name: petsi-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petsi
      - SPRING_DATASOURCE_USERNAME=petsi_user
      - SPRING_DATASOURCE_PASSWORD=petsi_pass
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/petsi

  mysql:
    image: mysql:8.0
    container_name: petsi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rladbgus02
      MYSQL_DATABASE: petsi
      MYSQL_USER: petsi_user
      MYSQL_PASSWORD: petsi_pass
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  mongodb:
    image: mongo:6
    container_name: petsi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mysql_data:
  mongo_data:
